spring:
  application:
    name: user-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://18.206.232.215:80/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

stonks-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

hub:
  finesURL: http://3.85.16.220:80
  regularURL: http://localhost:80
  adviceURL: http://54.242.157.107:80