spring:
  application:
    name: stonks-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/stonkdb
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true