spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  application:
    name: stonks-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
stonks-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
# Manual Setting
#stonks-service:
#  ribbon:
#    listOfServers: localhost:8787, localhost: 8989
#    eureka:
#      enabled: true



