spring:
  application:
    name: zuul-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ms-config-server

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://18.206.232.215:80/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    auth-service:
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
      path: /auth/**
      service-id: security-service
    gallery-service:
      path: /stonks/**
      service-id: stonks-service
    user-service:
      path: /users/**
      service-id: user-service